### ISSUE TITLE
CANNOT ADD NEW FLIGHTS ON NEW DATE 

### ISSUE THREAD

**Issue by Varunmnx** [ayush9304/Flight#1]
tried to add new flights but date is not properly updating
for example how to  add flights as a  admin  column for date is absent

**Comment by ayush9304** [comment]
Flights details does not contains which date it will be flying, instead it contains which day of the week it will be flying assuming that flight is operating regularly and not on just a specific date. (See figure.)

<img width="437" alt="image" src="https://user-images.githubusercontent.com/56977388/155133260-cbb73405-7a8e-422e-94ee-20345370d5e3.png">

So when user searches for flight on specific date then it automatically get the weekday of that date and search for flight on that weekday between origin & destination.
